just dont fail this

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -168,7 +168,7 @@ main() {
   fi
 
   echo "Loading encrypted files"
-  yadm decrypt
+  yadm decrypt || true # allow failure for non-nacho users
 
 }
 
